language: dart
sudo: false
dart:
  - dev
  - stable
  - 1.21.1
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test: --platform vm
    xvfb: false
  - test: --platform firefox
  - test: --platform dartium
    install_dartium: true
  - dartfmt
  - dartanalyzer
