language: dart

dart:
  - dev
  - 1.23.0

dart_task:
  - test: --platform vm
    xvfb: false
  - test: --platform firefox
  - dartfmt
  - dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
