name: http_parser
version: 4.0.0
description: >-
  A platform-independent package for parsing and serializing HTTP formats.
homepage: https://github.com/dart-lang/http_parser

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  charcode: ^1.2.0
  collection: ^1.15.0
  source_span: ^1.8.0
  string_scanner: ^1.1.0
  typed_data: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0-nullsafety.4
