name: http_parser
version: 3.1.2-dev
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/http_parser
description: >
  A platform-independent package for parsing and serializing HTTP formats.
environment:
  sdk: ">=1.21.0 <2.0.0-dev.infinity"
dependencies:
  charcode: "^1.1.0"
  collection: ">=0.9.1 <2.0.0"
  source_span: "^1.0.0"
  string_scanner: ">=0.0.0 <2.0.0"
  typed_data: "^1.1.0"
dev_dependencies:
  test: "^0.12.0"
